### PR TITLE
update setup guide link to be more general

### PR DESCRIPTION
**Pull request by phritz**
We have self-signup now so its not just server setup, it's setup.

progress towards https://github.com/rocicorp/repc/issues/269

### CODE REVIEW

**Comment by aboodman** [comment]
In what sense is the content of the SERVER_SETUP.md document broader than setting up the server? I don't get it.

**Comment by phritz** [comment]
> In what sense is the content of the SERVER_SETUP.md document broader than setting up the server? I don't get it.

It's going to cover setting up **client and server**. Setting up the client is not currently explained explicitly anywhere. As I am tired of pointing out by this point, https://github.com/rocicorp/replicache-sdk-js/blob/main/README.md is focused on getting a client up and running for **the TODO app backend**, not your own backend. Yes people can take what's there and infer how to get it to work for their own backend, but it's going to be much better if we include clear instructions to how to do that, instead of instructions for a TODO backend and then just trust that they can understand how to change that for their own backend.

**Comment by phritz** [comment]
An equivalent solution would be of course to break the js page into two
separate pages, one for walking through getting a client  running against
the todo backend and a second for setting a client up for your own backend.

**Comment by aboodman** [comment]
I spent a bunch of time today trying to understand what you are proposing and failing. I don't have time to try and understand anymore, but if you want to put together a PR I will take a look. Per our norms it's also fine to start changing stuff we can always roll it back.

Sorry!

**Comment by phritz** [comment]
OK I will put together a PR, likely in the replicache repo, and will move some content there for the purpose of showing what I mean as part of a single PR, even if the content would actually live in different repos in the end state.

**Pull request closed without merging**
